GET http://localhost:5000/findAll
Accept: application/json

###
POST http://localhost:5000/api/create
Content-Type: application/json

{
  "name": "John Doe",
  "password": "123456",
  "email": "foo@example.com"

}


