GET http://localhost:5000/findAll
Accept: application/json

###
POST http://localhost:5000/create
Content-Type: application/json

{
  "name": "John Doe",
  "email": "foo@example.com",
  "téléphone": 1234567890
}


