version: '3'
services:
  my-app:
    container_name: "dossier-client"
    image: nodeapp1.azurecr.io/microservice:1.0.1
    build: .
    ports:
        - 3000:5000
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"
volumes:
  mongo-data:
    driver: local
